version: '3'

volumes:
  vol1-emqx-data:
  vol1-emqx-etc:
  vol1-emqx-log:
  
  vol2-emqx-data:
  vol2-emqx-etc:
  vol2-emqx-log:

services:
  emqx1:
    image: emqx:5.0.26
    container_name: emqx1
    environment:
    - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083 
    volumes:
      - vol1-emqx-data:/opt/emqx/data
      - vol1-emqx-etc:/opt/emqx/etc
      - vol1-emqx-log:/opt/emqx/log
  emqx2:
    image: emqx:5.0.26
    container_name: emqx2
    environment:
    - "EMQX_NODE_NAME=emqx@node2.emqx.io"
    - "EMQX_CLUSTER__DISCOVERY_STRATEGY=static"
    - "EMQX_CLUSTER__STATIC__SEEDS=[emqx@node1.emqx.io,emqx@node2.emqx.io]"
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx_ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
    volumes:
      - vol2-emqx-data:/opt/emqx/data
      - vol2-emqx-etc:/opt/emqx/etc
      - vol2-emqx-log:/opt/emqx/log
