// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.example.iot_app.proto;

public interface ChangeLedColorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ir.mahmoud.iot_attendance_system.ChangeLedColorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string device_id = 1;</code>
   * @return The deviceId.
   */
  String getDeviceId();
  /**
   * <code>string device_id = 1;</code>
   * @return The bytes for deviceId.
   */
  com.google.protobuf.ByteString
      getDeviceIdBytes();

  /**
   * <code>int32 red = 2;</code>
   * @return The red.
   */
  int getRed();

  /**
   * <code>int32 green = 3;</code>
   * @return The green.
   */
  int getGreen();

  /**
   * <code>int32 blue = 4;</code>
   * @return The blue.
   */
  int getBlue();
}
