// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.example.iot_app.proto;

public interface GetDeviceIdsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ir.mahmoud.iot_attendance_system.GetDeviceIdsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Device devices = 1;</code>
   */
  java.util.List<Device>
      getDevicesList();
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Device devices = 1;</code>
   */
  Device getDevices(int index);
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Device devices = 1;</code>
   */
  int getDevicesCount();
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Device devices = 1;</code>
   */
  java.util.List<? extends DeviceOrBuilder>
      getDevicesOrBuilderList();
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Device devices = 1;</code>
   */
  DeviceOrBuilder getDevicesOrBuilder(
      int index);
}
