// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.example.iot_app.proto;

public interface GetPresentEmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ir.mahmoud.iot_attendance_system.GetPresentEmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Employee employees = 1;</code>
   */
  java.util.List<Employee>
      getEmployeesList();
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Employee employees = 1;</code>
   */
  Employee getEmployees(int index);
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Employee employees = 1;</code>
   */
  int getEmployeesCount();
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Employee employees = 1;</code>
   */
  java.util.List<? extends EmployeeOrBuilder>
      getEmployeesOrBuilderList();
  /**
   * <code>repeated .ir.mahmoud.iot_attendance_system.Employee employees = 1;</code>
   */
  EmployeeOrBuilder getEmployeesOrBuilder(
      int index);
}
