// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.example.iot_app.proto;

/**
 * Protobuf type {@code ir.mahmoud.iot_attendance_system.LedColorResponse}
 */
public final class LedColorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ir.mahmoud.iot_attendance_system.LedColorResponse)
    LedColorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LedColorResponse.newBuilder() to construct.
  private LedColorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LedColorResponse() {
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LedColorResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LedColorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            red_ = input.readInt32();
            break;
          }
          case 16: {

            green_ = input.readInt32();
            break;
          }
          case 24: {

            blue_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LedColorResponse_descriptor;
  }

  @Override
  protected FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LedColorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LedColorResponse.class, Builder.class);
  }

  public static final int RED_FIELD_NUMBER = 1;
  private int red_;
  /**
   * <code>int32 red = 1;</code>
   * @return The red.
   */
  @Override
  public int getRed() {
    return red_;
  }

  public static final int GREEN_FIELD_NUMBER = 2;
  private int green_;
  /**
   * <code>int32 green = 2;</code>
   * @return The green.
   */
  @Override
  public int getGreen() {
    return green_;
  }

  public static final int BLUE_FIELD_NUMBER = 3;
  private int blue_;
  /**
   * <code>int32 blue = 3;</code>
   * @return The blue.
   */
  @Override
  public int getBlue() {
    return blue_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (red_ != 0) {
      output.writeInt32(1, red_);
    }
    if (green_ != 0) {
      output.writeInt32(2, green_);
    }
    if (blue_ != 0) {
      output.writeInt32(3, blue_);
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (red_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, red_);
    }
    if (green_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, green_);
    }
    if (blue_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, blue_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LedColorResponse)) {
      return super.equals(obj);
    }
    LedColorResponse other = (LedColorResponse) obj;

    if (getRed()
        != other.getRed()) return false;
    if (getGreen()
        != other.getGreen()) return false;
    if (getBlue()
        != other.getBlue()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RED_FIELD_NUMBER;
    hash = (53 * hash) + getRed();
    hash = (37 * hash) + GREEN_FIELD_NUMBER;
    hash = (53 * hash) + getGreen();
    hash = (37 * hash) + BLUE_FIELD_NUMBER;
    hash = (53 * hash) + getBlue();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LedColorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LedColorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LedColorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LedColorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LedColorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LedColorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LedColorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LedColorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LedColorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LedColorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LedColorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LedColorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LedColorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ir.mahmoud.iot_attendance_system.LedColorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ir.mahmoud.iot_attendance_system.LedColorResponse)
      LedColorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LedColorResponse_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LedColorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LedColorResponse.class, Builder.class);
    }

    // Construct using com.example.iot_app.proto.LedColorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      red_ = 0;

      green_ = 0;

      blue_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LedColorResponse_descriptor;
    }

    @Override
    public LedColorResponse getDefaultInstanceForType() {
      return LedColorResponse.getDefaultInstance();
    }

    @Override
    public LedColorResponse build() {
      LedColorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public LedColorResponse buildPartial() {
      LedColorResponse result = new LedColorResponse(this);
      result.red_ = red_;
      result.green_ = green_;
      result.blue_ = blue_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LedColorResponse) {
        return mergeFrom((LedColorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LedColorResponse other) {
      if (other == LedColorResponse.getDefaultInstance()) return this;
      if (other.getRed() != 0) {
        setRed(other.getRed());
      }
      if (other.getGreen() != 0) {
        setGreen(other.getGreen());
      }
      if (other.getBlue() != 0) {
        setBlue(other.getBlue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LedColorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LedColorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int red_ ;
    /**
     * <code>int32 red = 1;</code>
     * @return The red.
     */
    @Override
    public int getRed() {
      return red_;
    }
    /**
     * <code>int32 red = 1;</code>
     * @param value The red to set.
     * @return This builder for chaining.
     */
    public Builder setRed(int value) {
      
      red_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 red = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRed() {
      
      red_ = 0;
      onChanged();
      return this;
    }

    private int green_ ;
    /**
     * <code>int32 green = 2;</code>
     * @return The green.
     */
    @Override
    public int getGreen() {
      return green_;
    }
    /**
     * <code>int32 green = 2;</code>
     * @param value The green to set.
     * @return This builder for chaining.
     */
    public Builder setGreen(int value) {
      
      green_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 green = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGreen() {
      
      green_ = 0;
      onChanged();
      return this;
    }

    private int blue_ ;
    /**
     * <code>int32 blue = 3;</code>
     * @return The blue.
     */
    @Override
    public int getBlue() {
      return blue_;
    }
    /**
     * <code>int32 blue = 3;</code>
     * @param value The blue to set.
     * @return This builder for chaining.
     */
    public Builder setBlue(int value) {
      
      blue_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 blue = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlue() {
      
      blue_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ir.mahmoud.iot_attendance_system.LedColorResponse)
  }

  // @@protoc_insertion_point(class_scope:ir.mahmoud.iot_attendance_system.LedColorResponse)
  private static final LedColorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LedColorResponse();
  }

  public static LedColorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LedColorResponse>
      PARSER = new com.google.protobuf.AbstractParser<LedColorResponse>() {
    @Override
    public LedColorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LedColorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LedColorResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LedColorResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public LedColorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

