// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service.proto

package com.example.iot_app.proto;

/**
 * Protobuf type {@code ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse}
 */
public final class LockOpenedHistoryResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse)
    LockOpenedHistoryResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LockOpenedHistoryResponse.newBuilder() to construct.
  private LockOpenedHistoryResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LockOpenedHistoryResponse() {
    histories_ = java.util.Collections.emptyList();
  }

  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new LockOpenedHistoryResponse();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private LockOpenedHistoryResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              histories_ = new java.util.ArrayList<history>();
              mutable_bitField0_ |= 0x00000001;
            }
            histories_.add(
                input.readMessage(history.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        histories_ = java.util.Collections.unmodifiableList(histories_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            LockOpenedHistoryResponse.class, Builder.class);
  }

  public interface historyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 server_timestamp = 1;</code>
     * @return The serverTimestamp.
     */
    long getServerTimestamp();

    /**
     * <code>int32 time_after_startup_sec = 2;</code>
     * @return The timeAfterStartupSec.
     */
    int getTimeAfterStartupSec();
  }
  /**
   * Protobuf type {@code ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history}
   */
  public static final class history extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history)
      historyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use history.newBuilder() to construct.
    private history(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private history() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new history();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private history(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              serverTimestamp_ = input.readInt64();
              break;
            }
            case 16: {

              timeAfterStartupSec_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_history_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_history_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              history.class, Builder.class);
    }

    public static final int SERVER_TIMESTAMP_FIELD_NUMBER = 1;
    private long serverTimestamp_;
    /**
     * <code>int64 server_timestamp = 1;</code>
     * @return The serverTimestamp.
     */
    @Override
    public long getServerTimestamp() {
      return serverTimestamp_;
    }

    public static final int TIME_AFTER_STARTUP_SEC_FIELD_NUMBER = 2;
    private int timeAfterStartupSec_;
    /**
     * <code>int32 time_after_startup_sec = 2;</code>
     * @return The timeAfterStartupSec.
     */
    @Override
    public int getTimeAfterStartupSec() {
      return timeAfterStartupSec_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverTimestamp_ != 0L) {
        output.writeInt64(1, serverTimestamp_);
      }
      if (timeAfterStartupSec_ != 0) {
        output.writeInt32(2, timeAfterStartupSec_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, serverTimestamp_);
      }
      if (timeAfterStartupSec_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timeAfterStartupSec_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof history)) {
        return super.equals(obj);
      }
      history other = (history) obj;

      if (getServerTimestamp()
          != other.getServerTimestamp()) return false;
      if (getTimeAfterStartupSec()
          != other.getTimeAfterStartupSec()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SERVER_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTimestamp());
      hash = (37 * hash) + TIME_AFTER_STARTUP_SEC_FIELD_NUMBER;
      hash = (53 * hash) + getTimeAfterStartupSec();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static history parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static history parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static history parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static history parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static history parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static history parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static history parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static history parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static history parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static history parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static history parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static history parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(history prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history)
        historyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_history_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_history_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                history.class, Builder.class);
      }

      // Construct using com.example.iot_app.proto.LockOpenedHistoryResponse.history.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        serverTimestamp_ = 0L;

        timeAfterStartupSec_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_history_descriptor;
      }

      @Override
      public history getDefaultInstanceForType() {
        return history.getDefaultInstance();
      }

      @Override
      public history build() {
        history result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public history buildPartial() {
        history result = new history(this);
        result.serverTimestamp_ = serverTimestamp_;
        result.timeAfterStartupSec_ = timeAfterStartupSec_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof history) {
          return mergeFrom((history)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(history other) {
        if (other == history.getDefaultInstance()) return this;
        if (other.getServerTimestamp() != 0L) {
          setServerTimestamp(other.getServerTimestamp());
        }
        if (other.getTimeAfterStartupSec() != 0) {
          setTimeAfterStartupSec(other.getTimeAfterStartupSec());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        history parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (history) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long serverTimestamp_ ;
      /**
       * <code>int64 server_timestamp = 1;</code>
       * @return The serverTimestamp.
       */
      @Override
      public long getServerTimestamp() {
        return serverTimestamp_;
      }
      /**
       * <code>int64 server_timestamp = 1;</code>
       * @param value The serverTimestamp to set.
       * @return This builder for chaining.
       */
      public Builder setServerTimestamp(long value) {
        
        serverTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 server_timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTimestamp() {
        
        serverTimestamp_ = 0L;
        onChanged();
        return this;
      }

      private int timeAfterStartupSec_ ;
      /**
       * <code>int32 time_after_startup_sec = 2;</code>
       * @return The timeAfterStartupSec.
       */
      @Override
      public int getTimeAfterStartupSec() {
        return timeAfterStartupSec_;
      }
      /**
       * <code>int32 time_after_startup_sec = 2;</code>
       * @param value The timeAfterStartupSec to set.
       * @return This builder for chaining.
       */
      public Builder setTimeAfterStartupSec(int value) {
        
        timeAfterStartupSec_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 time_after_startup_sec = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimeAfterStartupSec() {
        
        timeAfterStartupSec_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history)
    }

    // @@protoc_insertion_point(class_scope:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history)
    private static final history DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new history();
    }

    public static history getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<history>
        PARSER = new com.google.protobuf.AbstractParser<history>() {
      @Override
      public history parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new history(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<history> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<history> getParserForType() {
      return PARSER;
    }

    @Override
    public history getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int HISTORIES_FIELD_NUMBER = 1;
  private java.util.List<history> histories_;
  /**
   * <pre>
   *  string first_name = 2;
   *  string last_name = 3 ;
   * </pre>
   *
   * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
   */
  @Override
  public java.util.List<history> getHistoriesList() {
    return histories_;
  }
  /**
   * <pre>
   *  string first_name = 2;
   *  string last_name = 3 ;
   * </pre>
   *
   * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
   */
  @Override
  public java.util.List<? extends historyOrBuilder>
      getHistoriesOrBuilderList() {
    return histories_;
  }
  /**
   * <pre>
   *  string first_name = 2;
   *  string last_name = 3 ;
   * </pre>
   *
   * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
   */
  @Override
  public int getHistoriesCount() {
    return histories_.size();
  }
  /**
   * <pre>
   *  string first_name = 2;
   *  string last_name = 3 ;
   * </pre>
   *
   * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
   */
  @Override
  public history getHistories(int index) {
    return histories_.get(index);
  }
  /**
   * <pre>
   *  string first_name = 2;
   *  string last_name = 3 ;
   * </pre>
   *
   * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
   */
  @Override
  public historyOrBuilder getHistoriesOrBuilder(
      int index) {
    return histories_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < histories_.size(); i++) {
      output.writeMessage(1, histories_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < histories_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, histories_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof LockOpenedHistoryResponse)) {
      return super.equals(obj);
    }
    LockOpenedHistoryResponse other = (LockOpenedHistoryResponse) obj;

    if (!getHistoriesList()
        .equals(other.getHistoriesList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getHistoriesCount() > 0) {
      hash = (37 * hash) + HISTORIES_FIELD_NUMBER;
      hash = (53 * hash) + getHistoriesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static LockOpenedHistoryResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockOpenedHistoryResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockOpenedHistoryResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockOpenedHistoryResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockOpenedHistoryResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static LockOpenedHistoryResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static LockOpenedHistoryResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LockOpenedHistoryResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static LockOpenedHistoryResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static LockOpenedHistoryResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static LockOpenedHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static LockOpenedHistoryResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(LockOpenedHistoryResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse)
      LockOpenedHistoryResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LockOpenedHistoryResponse.class, Builder.class);
    }

    // Construct using com.example.iot_app.proto.LockOpenedHistoryResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getHistoriesFieldBuilder();
      }
    }
    @Override
    public Builder clear() {
      super.clear();
      if (historiesBuilder_ == null) {
        histories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        historiesBuilder_.clear();
      }
      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MyServiceProto.internal_static_ir_mahmoud_iot_attendance_system_LockOpenedHistoryResponse_descriptor;
    }

    @Override
    public LockOpenedHistoryResponse getDefaultInstanceForType() {
      return LockOpenedHistoryResponse.getDefaultInstance();
    }

    @Override
    public LockOpenedHistoryResponse build() {
      LockOpenedHistoryResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public LockOpenedHistoryResponse buildPartial() {
      LockOpenedHistoryResponse result = new LockOpenedHistoryResponse(this);
      int from_bitField0_ = bitField0_;
      if (historiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          histories_ = java.util.Collections.unmodifiableList(histories_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.histories_ = histories_;
      } else {
        result.histories_ = historiesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof LockOpenedHistoryResponse) {
        return mergeFrom((LockOpenedHistoryResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(LockOpenedHistoryResponse other) {
      if (other == LockOpenedHistoryResponse.getDefaultInstance()) return this;
      if (historiesBuilder_ == null) {
        if (!other.histories_.isEmpty()) {
          if (histories_.isEmpty()) {
            histories_ = other.histories_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureHistoriesIsMutable();
            histories_.addAll(other.histories_);
          }
          onChanged();
        }
      } else {
        if (!other.histories_.isEmpty()) {
          if (historiesBuilder_.isEmpty()) {
            historiesBuilder_.dispose();
            historiesBuilder_ = null;
            histories_ = other.histories_;
            bitField0_ = (bitField0_ & ~0x00000001);
            historiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getHistoriesFieldBuilder() : null;
          } else {
            historiesBuilder_.addAllMessages(other.histories_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      LockOpenedHistoryResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (LockOpenedHistoryResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<history> histories_ =
      java.util.Collections.emptyList();
    private void ensureHistoriesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        histories_ = new java.util.ArrayList<history>(histories_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        history, history.Builder, historyOrBuilder> historiesBuilder_;

    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public java.util.List<history> getHistoriesList() {
      if (historiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(histories_);
      } else {
        return historiesBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public int getHistoriesCount() {
      if (historiesBuilder_ == null) {
        return histories_.size();
      } else {
        return historiesBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public history getHistories(int index) {
      if (historiesBuilder_ == null) {
        return histories_.get(index);
      } else {
        return historiesBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder setHistories(
        int index, history value) {
      if (historiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoriesIsMutable();
        histories_.set(index, value);
        onChanged();
      } else {
        historiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder setHistories(
        int index, history.Builder builderForValue) {
      if (historiesBuilder_ == null) {
        ensureHistoriesIsMutable();
        histories_.set(index, builderForValue.build());
        onChanged();
      } else {
        historiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder addHistories(history value) {
      if (historiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoriesIsMutable();
        histories_.add(value);
        onChanged();
      } else {
        historiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder addHistories(
        int index, history value) {
      if (historiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureHistoriesIsMutable();
        histories_.add(index, value);
        onChanged();
      } else {
        historiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder addHistories(
        history.Builder builderForValue) {
      if (historiesBuilder_ == null) {
        ensureHistoriesIsMutable();
        histories_.add(builderForValue.build());
        onChanged();
      } else {
        historiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder addHistories(
        int index, history.Builder builderForValue) {
      if (historiesBuilder_ == null) {
        ensureHistoriesIsMutable();
        histories_.add(index, builderForValue.build());
        onChanged();
      } else {
        historiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder addAllHistories(
        Iterable<? extends history> values) {
      if (historiesBuilder_ == null) {
        ensureHistoriesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, histories_);
        onChanged();
      } else {
        historiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder clearHistories() {
      if (historiesBuilder_ == null) {
        histories_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        historiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public Builder removeHistories(int index) {
      if (historiesBuilder_ == null) {
        ensureHistoriesIsMutable();
        histories_.remove(index);
        onChanged();
      } else {
        historiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public history.Builder getHistoriesBuilder(
        int index) {
      return getHistoriesFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public historyOrBuilder getHistoriesOrBuilder(
        int index) {
      if (historiesBuilder_ == null) {
        return histories_.get(index);  } else {
        return historiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public java.util.List<? extends historyOrBuilder>
         getHistoriesOrBuilderList() {
      if (historiesBuilder_ != null) {
        return historiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(histories_);
      }
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public history.Builder addHistoriesBuilder() {
      return getHistoriesFieldBuilder().addBuilder(
          history.getDefaultInstance());
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public history.Builder addHistoriesBuilder(
        int index) {
      return getHistoriesFieldBuilder().addBuilder(
          index, history.getDefaultInstance());
    }
    /**
     * <pre>
     *  string first_name = 2;
     *  string last_name = 3 ;
     * </pre>
     *
     * <code>repeated .ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse.history histories = 1;</code>
     */
    public java.util.List<history.Builder>
         getHistoriesBuilderList() {
      return getHistoriesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        history, history.Builder, historyOrBuilder>
        getHistoriesFieldBuilder() {
      if (historiesBuilder_ == null) {
        historiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            history, history.Builder, historyOrBuilder>(
                histories_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        histories_ = null;
      }
      return historiesBuilder_;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse)
  }

  // @@protoc_insertion_point(class_scope:ir.mahmoud.iot_attendance_system.LockOpenedHistoryResponse)
  private static final LockOpenedHistoryResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new LockOpenedHistoryResponse();
  }

  public static LockOpenedHistoryResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<LockOpenedHistoryResponse>
      PARSER = new com.google.protobuf.AbstractParser<LockOpenedHistoryResponse>() {
    @Override
    public LockOpenedHistoryResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new LockOpenedHistoryResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<LockOpenedHistoryResponse> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<LockOpenedHistoryResponse> getParserForType() {
    return PARSER;
  }

  @Override
  public LockOpenedHistoryResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

